# -*- coding: utf-8 -*-
"""Numpy1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZnOboteapWZ7XDT1GAxxIa7ted1s-Jt-
"""

import numpy as np
print(np.__version__)

a1=np.array([1,2,3,4,5])
print(a1)

type(a1)

a1.shape

a1.size

a2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a2)

type(a2)

a2.shape

a2.size

a2.ndim

z1=np.zeros([4,3])
print(z1)

z2=np.zeros(10)
print(z2)

z1=np.ones([4,3])
print(z1)

z1=np.zeros(3,dtype='int')
print(z1)

z1.shape

z1.size

z1.ndim

type(z1)

z2=np.ones((2,3,4),dtype=int)
z2

f1=np.full((3,4),5)
f1

a=np.array([12,21,33])
b=np.array([10,20,30])
print(a+b)

a=np.array([12,21,33])
b=np.array([10,20,30])
print(a-b)

a=np.array([12,21,33])
b=np.array([10,20,30])
print(a/b)

a=np.array([12,21,33])
b=np.array([10,20,30])
sub=np.power(a,b)
sub

a=np.array([12,21,33])
b=np.array([10,20,30])
sub=np.mod(a,b)
sub

import matplotlib.pyplot as plt

years=[2010,2011,2012,2013,2014]
yield_apples=[0.89,1.5,1.1,1.65,1.21]
plt.plot(years,yield_apples)

plt.plot(years,yield_apples,marker='o')
plt.xlabel('year')
plt.ylabel('yield_apples')

year=range(2010,2018)
apples=[0.895,0.91,0.919,0.926,0.929,0.931,0.934,0.936]
oranges=[0.962,0.941,0.939,0.937,0.937,0.939,0.94,0.943]
plt.plot(year,apples,marker='o')
plt.plot(year,oranges,marker='o')
plt.xlabel('year')
plt.ylabel('yield_apples')
plt.legend(['apples','oranges'])

plt.plot(year,apples,marker='o',label='apples')
plt.plot(year,oranges,marker='x',label='oranges')
plt.xlabel('year')
plt.ylabel('yield_apples')
plt.legend()

x=plt.plot(year,apples,marker='s',c='b',ls='-',lw=2,ms=8,mew=2,mec='navy')
plt.plot(year,oranges,marker='o',c='r',ls='--',lw=2,ms=8,mew=2,alpha=0.5)
plt.xlabel('year')
plt.ylabel('yield')
plt.title('crop yield in kanto')
plt.legend(['apples','oranges'])

x=[3,1,5,8,6,4,2,3]
y=[3,2,1,4,5,6,7,8]
plt.bar(x,y)
plt.legend(["bar"])
plt.title("bar chart")
plt.show()

x=[3,1,5,8,6,4,2,3]
y=[3,2,1,4,5,6,7,8]
plt.scatter(x,y)
plt.legend(["scatter"])
plt.title("scatter chart")
plt.show()

x=[3,1,5,8,6,4,2,3]
y=[3,2,1,4,5,6,7,8]
plt.pie(x)
plt.legend(["pie"])
plt.title("pie chart")
plt.show()